include $(GOROOT)/src/Make.inc

TARG=vimini-$(XENVERSION)
GOFILES=main.go
GCIMPORTS=-I../../pkg/xen/_obj/$(XENVERSION)
LDIMPORTS=-L../../pkg/xen/_obj/$(XENVERSION)
CGO_LDFLAGS=-L../../deps/xen/$(XENVERSION)/lib -lxenctrl -lxenstore

include $(GOROOT)/src/Make.cmd