all:
	$(MAKE) -f Makefile.common XENVERSION=3.0
	$(MAKE) -f Makefile.common XENVERSION=3.4
	$(MAKE) -f Makefile.common XENVERSION=4.0

clean:
	$(MAKE) -f Makefile.common XENVERSION=3.0 clean
	$(MAKE) -f Makefile.common XENVERSION=3.4 clean
	$(MAKE) -f Makefile.common XENVERSION=4.0 clean
