include $(GOROOT)/src/Make.inc

TARG=$(XENVERSION)/vimini/xen
GOFILES=domain.go
CGOFILES=xen.go
CGO_CFLAGS=-I../../deps/xen/$(XENVERSION)/include
CGO_LDFLAGS=-L../../deps/xen/$(XENVERSION)/lib -lxenctrl -lxenstore

include $(GOROOT)/src/Make.pkg